### ISSUE TITLE
No fril vanilla docker already exists

### ISSUE THREAD

**Issue by PavelSosin-320** [conioh/Docker-Windows-Linux#1]
No frill vanilla docker already exists and can be installed on Ubuntu 20.04 and Centos7 WSL in less than 2hours. I saved my Centos7 image in Cloud storage. They don't support Windows containers or ARM containers but based on formidable Linux distros instead of cramped Alpine. It's OK for me that it can use almost all Computer' memory. In the production environment, Cloud application will land on RHEL running cluster in 99% of cases.
But it is only an intermediate solution because the support of Docker will be revoked by RedHat soon. New Micro8s is built on Podman already

**Comment by conioh** [comment]
I'm don't understand the issue.

Did I imply even remotely something other than that "no fril vanilla docker already exists"? Is it not what's written? Did I not propose to install it?

**Comment by conioh** [comment]
I don't understand the issue.

Did I imply even remotely something other than that "no fril vanilla docker already exists"? Is it not what's written? Did I not propose to install it?

**Comment by PavelSosin-320** [comment]
The vanilla docker can be installed in many WSL Linux distros from Microsoft store just like on Linux distros installed on the bare metal machine, for example, Ubuntu 20.04, CentnOS7. The installation procedure is almost the same as the regular installation. As a result, the user has a recent Docker version on the Linux upgraded to the recent version without any connection with the Docker Desktop version release. Docker Desktop for Windows provides many features rarely used in daily life but adding complexity to maintenance. It is based on Alpine Linux, the distro developed for certain purposes but lacks many standard Linux utilities. Docker integration with other distros is very complex and misses the simple fact that all WSL 2 distros are the same singleton VM, have the same singleton Microsoft Kernel and sharing the same host network. Ports opened in the different distro instances have to be unique overall because they are exposed to the same Host machine Local interface. It doesn't require any "integration". In most cases, packages for all distros duplicate each other, running different applications with TCP networking will cause port conflict.
My conclusion that it is not possible currently to run several Docker engines in parallel using WSL on the same Windows machine.
But having a Lightweight independent docker with minimal integration with Windows is possible and very useful.

**Comment by conioh** [comment]
I thought about it long and hard and still don't understand _what do you want from me_.
Is there a request here that I do something?

**Comment by PavelSosin-320** [comment]
SOLVED: The issue is solved via the correct support of docker context. Now users can configure context and use any available Docker provider without hard binding with "fixed" Docker Desktop-for-Win installed locally including all features unusable in the user-specific scenario and user-specific network layout. Docker context is supported by VSCode too.
